upstream crafter_delivery_backend {
    server crafter-delivery:8080 max_fails=1 fail_timeout=10s;
    server crafter-delivery-green:8080 backup;
}

server {
    listen 80;

    location / {
        set $target_site "jakefear";
        if ($host ~* "maiiavorobiova.com") {
            set $target_site "maiia-portfolio";
        }

        if ($arg_crafterSite = "") {
            rewrite ^/(.*)$ /$1?crafterSite=$target_site break;
        }
        
        proxy_pass http://crafter_delivery_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
